routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth');

Route::get('/ajax/getAccessToken/', 'ajax\getAccessToken@index');
Route::post('/ajax/getAccessToken/', 'ajax\getAccessToken@index');
Route::get('oauth', 'CreateAppointment@oauth')->name('oauthCallback');
Route::get('/home','HomeController@index');
Route::get('/coba','CheckAppointment@lol');
Route::post('/reset/password',function(){
	\Session::put('action_password_reset','reset');
	return response()->json('submit');
});
Route::post('/reset/password/confirm','Auth\ResetPasswordController@index');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('createapp', 'CreateAppointment');
    Route::get('/', 'HomeController@index');
    Route::get('/setting','AccountSetting@index');
    Route::get('/logout','Auth\LogoutController@getLogout');
    Route::post('/password/change','AccountSetting@passwordChange');
    Route::post('/setting/save','AccountSetting@update');
    Route::post('/setting/email',function(){
		\Session::put('action_mail_update','update');
		return response()->json('submit');
	});
	Route::get('locale/{locale}', function($locale) {
	    Session::put('locale',$locale);
	    return redirect()->back();
	});
});

Route::group(['middleware' => 'student'], function() {
    Route::get('/appointment/create/{username}', 'CreateAppointment@create');
    Route::get('/make/appointment/', 'ajax\setAppointment@index');
	Route::post('/make/appointment/', 'ajax\setAppointment@index');
	Route::post('/appointment/store/','CreateAppointment@store');
	Route::get('/appointment/store/','CreateAppointment@store');
	Route::get('/appointment/list','CheckAppointment@checkAppStudent');
	Route::get('/search/lecturer','ajax\searchLecturer@index');
	Route::post('/reschedule/deny/callback','CheckAppointment@setDenyCallback');
	Route::post('/reschedule/accept/callback','CheckAppointment@setAcceptCallback');
});

Route::group(['middleware' => 'lecturer'],function(){
	
	
	Route::get('/schedule/manage','LecturerSchedule@index');
	Route::get('/appointment/check','CheckAppointment@checkAppLecturer');
	Route::post('/schedule/manage/save', 'LecturerSchedule@update');
	Route::post('/schedule/manage/create', 'LecturerSchedule@create');
	Route::post('/appointment/reschedule/callback','CheckAppointment@setRescheduleCallback');
	Route::post('/appointment/cancel/callback','CheckAppointment@setCancelCallback');
	
});

Route::get('ajax', function(){ return view('refreshToken'); });
Route::post('https://www.googleapis.com/oauth2/v4/token/','RefreshTokenController@post');

Auth::routes();
Route::resource('createapp', 'CreateAppointment');
Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'CreateAppointment@oauth']);

// Google Login
Route::get('/auth/redirect/google', 'SocialController@redirectToProvider');
Route::get('/callback/google/', 'SocialController@handleProviderCallback');

resources/views/calendar/createEvent.blade.php
@extends('layouts.base')
@section('content')
@include('varviewjs')
    <script>
        $(document).ready(function(){
            $("nav").hide();
            var at = null;
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            $.ajax({
                url: '/ajax/getAccessToken/',
                type: 'POST',
                data: {
                    _token: CSRF_TOKEN
                },
                dataType: 'JSON',
                success: function (data) { 
                    console.log(data);
                }
            });          
       });    
    </script>
    <style>
        tr{
            height: 30px;
        }
    </style>
    <br>    
    <form action="{{route('createapp.store')}}" method="POST" role="form">
        {{csrf_field()}}
        <legend>
            Create Appointment to {{$name}}
        </legend>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="title">
                        Name
                    </label>
                    <input class="form-control" name="title" placeholder="Name" value="{{ $myname }}" type="text" readonly>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="description">
                        Description
                    </label>
                    <br>
                    <select class="form-control" name="description">
                        <option value="Bimbingan">Bimbingan</option>
                        <option value="Konsultasi">Konsultasi</option>
                        <option value="Presentasi">Presentasi</option>
                    </select>
                    <textarea class="form-control" name="information" placeholder="Additional Information" type="text" rows="4" cols="50" required></textarea>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="place">
                        Place
                    </label>
                    <input class="form-control" name="place" placeholder="Place" type="text" rows="4" cols="50" readonly>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="description">
                    Choose Date & Time
                </label>              
                <div class="panel panel-default">
                    <div class="panel-body" id="calendarForm">
                        {!! $calendar->calendar() !!}
                    </div>
                    
                </div>
                <div>
                @if($error != "")
                    <p style="color:red;"><b>{{ $error }}</b></p>
                @endif
                </div>
            </div>
        </div>
<!--         <input type="hidden" name="atoken" id="atoken"> -->
        <!-- <input type="hidden" name="expires_in" value="3600"> -->
        <!-- <input type="hidden" name="rtoken" value={{$refresh_token}}> -->
       <!--  <input type="hidden" name="scope" value="https://www.googleapis.com/auth/calendar"> -->
        <div class="form-group">
            <input class="form-control" name="start_date" type="hidden" id="start_date" disabled>
        </div>
        <button class="btn btn-primary" type="submit" id="submit">
            Submit
        </button>
        <br>    
        <br>    

    </form>
    {!! $calendar->script() !!}
    
<script>
    $(document).ready(function(){
        
        showTime();
        $(".fc-next-button, .fc-prev-button, .fc-today-button").on("click",function(){
            showTime();
        })
        $(".fc-view").on('dragstart',function(e){
            e.preventDefault();
        }).attr('draggable','false');

    })

    function showTime(){
        var timeLoad = $('tr[data-time]').map( function() {
            return $(this).attr('data-time');
        }).get();
        $.each(timeLoad,function(index,value){
            $(".fc-content-col").append("<div class='button-grid'><p style='margin-bottom:0px;'>"+value+"</p></div>");
        })
    }
    console.log("{{route('createapp.store')}}");
    // $("#submit").on("click", function(){
    //     swal({
    //         title: "Success",
    //         text: "Your appointment success input",
    //         icon: "success",
    //         button: "Close!",
    //     });
    // })
</script>
@endsection